// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkGLgWgAgv7sECyQ8xJ6Z-iOen3I052OQ',
    appId: '1:825339002272:web:dc39c6e909cc68bcddb8c5',
    messagingSenderId: '825339002272',
    projectId: 'platform-for-evenets',
    authDomain: 'platform-for-evenets.firebaseapp.com',
    storageBucket: 'platform-for-evenets.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6-2Tsp_q-NQMTMTtlFjNa_8Anf6bGlMc',
    appId: '1:825339002272:android:76b91df31f81eceeddb8c5',
    messagingSenderId: '825339002272',
    projectId: 'platform-for-evenets',
    storageBucket: 'platform-for-evenets.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChb0yxaP8RSLOvJ03MWv3u0XuBIkyumNk',
    appId: '1:825339002272:ios:e9745d63078eb049ddb8c5',
    messagingSenderId: '825339002272',
    projectId: 'platform-for-evenets',
    storageBucket: 'platform-for-evenets.firebasestorage.app',
    iosBundleId: 'com.example.avto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChb0yxaP8RSLOvJ03MWv3u0XuBIkyumNk',
    appId: '1:825339002272:ios:e9745d63078eb049ddb8c5',
    messagingSenderId: '825339002272',
    projectId: 'platform-for-evenets',
    storageBucket: 'platform-for-evenets.firebasestorage.app',
    iosBundleId: 'com.example.avto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkGLgWgAgv7sECyQ8xJ6Z-iOen3I052OQ',
    appId: '1:825339002272:web:bebb884d121b985cddb8c5',
    messagingSenderId: '825339002272',
    projectId: 'platform-for-evenets',
    authDomain: 'platform-for-evenets.firebaseapp.com',
    storageBucket: 'platform-for-evenets.firebasestorage.app',
  );

}