// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO4QR-4oM2q9QsH63S7Xi24igAZYGej14',
    appId: '1:174217211358:web:c07848ac6203752006814f',
    messagingSenderId: '174217211358',
    projectId: 'events-3ea95',
    authDomain: 'events-3ea95.firebaseapp.com',
    storageBucket: 'events-3ea95.firebasestorage.app',
    measurementId: 'G-HQRZ1H2V2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE7hJbjC_X9em5uEErhSoDdjPF44CDHBs',
    appId: '1:174217211358:android:de9b8954160282ba06814f',
    messagingSenderId: '174217211358',
    projectId: 'events-3ea95',
    storageBucket: 'events-3ea95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8RrliV5-WLsG1ZYEStPK2yOyo7L1fcGw',
    appId: '1:174217211358:ios:0b0f79579a06e4ed06814f',
    messagingSenderId: '174217211358',
    projectId: 'events-3ea95',
    storageBucket: 'events-3ea95.firebasestorage.app',
    iosBundleId: 'com.example.avto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8RrliV5-WLsG1ZYEStPK2yOyo7L1fcGw',
    appId: '1:174217211358:ios:0b0f79579a06e4ed06814f',
    messagingSenderId: '174217211358',
    projectId: 'events-3ea95',
    storageBucket: 'events-3ea95.firebasestorage.app',
    iosBundleId: 'com.example.avto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO4QR-4oM2q9QsH63S7Xi24igAZYGej14',
    appId: '1:174217211358:web:6919fb5a56a1776706814f',
    messagingSenderId: '174217211358',
    projectId: 'events-3ea95',
    authDomain: 'events-3ea95.firebaseapp.com',
    storageBucket: 'events-3ea95.firebasestorage.app',
    measurementId: 'G-YD4PCRDCQF',
  );
}
